In [1]:
import numpy as np

# Numpy intro

why is it efficient? It has C implementation.

# Creating arrays

what is a tensor? $(T_{i_1,\dots,i_d})_{i_1 \in [n_1], \dots, i_d \in [n_d]}$ with $T_{i_1,\dots,i_d} \in  \mathbb{R}.$
* Multidimensional array of numbers.
* Multilinear form on $\mathbb{R}^{n_1} \times \dots \times \mathbb{R}^{n_d}.$

1D tensor is a vector. 2D is a matrix.

 Different ways to create NumPy arrays (np.array(), np.zeros(), np.ones(), np.arange(), np.linspace(), np.random)

In [2]:
my_array = np.array([3,4,5,5,6])
print(my_array.dtype)


my_array = np.array([3,4,5.1 ,5,6])
print(my_array.dtype)

my_array = np.array([True, False, True])
print(my_array.dtype)


int64
float64
bool


In [3]:
my_ones_i_j = np.ones((2,4))
print(my_ones_i_j)
print('--------------------')
my_ones_i_j_k = np.ones((3,2,4))
print(my_ones_i_j_k)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
--------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [4]:
np.random.seed(42)
my_random_integers_i_j = np.random.randint(0,10, size=(3,4))
print(my_random_integers_i_j)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]


In [5]:
np.random.seed(42)
my_gunbel_i_j_k_l = np.random.gumbel(0,2, size=(2,3,4,5))

print(my_gunbel_i_j_k_l.round(1))

[[[[ 1.5 -2.2 -0.6  0.2  3.5]
   [ 3.5  5.6 -1.4  0.2 -0.4]
   [ 7.7 -2.5 -1.2  2.9  3.2]
   [ 3.2  2.   0.6  1.1  2.1]]

  [[ 0.1  3.8  2.1  1.6  1. ]
   [-0.9  3.   0.7  0.2  6.1]
   [ 0.1  3.4  5.4 -2.2 -2.4]
   [-1.   2.   4.6 -0.3  1.1]]

  [[ 4.1  0.8  6.7 -1.8  2.4]
   [-0.2  2.   0.6  0.5  3.2]
   [-2.5 -0.8 -2.1 -1.6  0.2]
   [-1.9  4.8  3.   6.1  1.9]]]


 [[[ 1.4  2.3 -1.1  1.6  2.2]
   [ 0.5  3.8 -1.   5.1 -2.9]
   [-0.8  3.  10.4 -1.  -0.4]
   [-0.5 -0.8  5.1  1.6  4.2]]

  [[-1.4  0.   1.8  5.4  2. ]
   [ 1.9 -0.5 -0.  -1.6  0.9]
   [ 4.1 -0.4 -0.7  0.4 -0.8]
   [ 0.8  0.6  1.2  7.3  4.3]]

  [[ 6.9 -0.   1.9  0.7 -1.7]
   [ 2.5  1.3 -0.7  2.7  5. ]
   [ 2.1  3.5 -2.  -1.  -0. ]
   [-1.4 -1.   3.2 -1.6  0.5]]]]


Array attributes: shape, size, dtype, ndim

In [6]:
print(my_ones_i_j.shape)
print(my_gunbel_i_j_k_l.shape)

(2, 4)
(2, 3, 4, 5)


In [7]:
print(my_ones_i_j.size)
print(my_gunbel_i_j_k_l.size)

8
120


In [8]:
print(my_ones_i_j.ndim)
print(my_gunbel_i_j_k_l.ndim)

2
4


Array methods: mean(),sum(), max(), argmax()

$S_i = \sum_j A_{ij}$

In [9]:
np.random.seed(42)
my_random_integers_i_j = np.random.randint(0,10, size=(100,150))

sum_i = my_random_integers_i_j.sum(1)
print(sum_i.shape)

(100,)


$M_{ik} = \arg \max_{j}\{A_{ijk}\} $ (breaking ties in favour of lower $j$)

In [10]:
np.random.seed(42)
my_array = np.random.rand(2,5,10)
print(my_array.round(2))
print('-----------------')
print(my_array.argmax(1))

[[[0.37 0.95 0.73 0.6  0.16 0.16 0.06 0.87 0.6  0.71]
  [0.02 0.97 0.83 0.21 0.18 0.18 0.3  0.52 0.43 0.29]
  [0.61 0.14 0.29 0.37 0.46 0.79 0.2  0.51 0.59 0.05]
  [0.61 0.17 0.07 0.95 0.97 0.81 0.3  0.1  0.68 0.44]
  [0.12 0.5  0.03 0.91 0.26 0.66 0.31 0.52 0.55 0.18]]

 [[0.97 0.78 0.94 0.89 0.6  0.92 0.09 0.2  0.05 0.33]
  [0.39 0.27 0.83 0.36 0.28 0.54 0.14 0.8  0.07 0.99]
  [0.77 0.2  0.01 0.82 0.71 0.73 0.77 0.07 0.36 0.12]
  [0.86 0.62 0.33 0.06 0.31 0.33 0.73 0.64 0.89 0.47]
  [0.12 0.71 0.76 0.56 0.77 0.49 0.52 0.43 0.03 0.11]]]
-----------------
[[2 1 1 3 3 3 4 0 3 0]
 [0 0 0 0 4 0 2 1 3 1]]


# Array Indexing, Slicing, and Reshaping

Basic indexing and slicing

In [11]:
np.random.seed(42)
my_array_i_j_k = np.random.randint(0,10, size=(5,10,9))

print(my_array_i_j_k.shape)
print(my_array_i_j_k[2:,-3:].shape)

(5, 10, 9)
(3, 3, 9)


Fancy indexing

You got a tensor $(T_{i_1,\dots,i_d})_{i_1 \in [D_1], \dots, i_d \in [D_d]}$ and also $k\leq d$ (index) tensors $N^\ell_{j_1,\dots,j_m}$ which are of the same shape and are such that $N^\ell_{j_1,\dots,j_m} \in [D_\ell],$ so that the $\ell$-th tensor $N^\ell$ picks the indeces from the $\ell$-th dimension of $T$. The resulting tensor will have the dimension of the indexing tensors concatenated to the dimensions of the non indexed dimensions of $T.$

The order of the dimensions is preserved if you index adjacent dimensions. Otherwise the new dimensions are stucked on the left of the non-indexed dimensions.

$T_{ijkm}, N^2_{pq},N^3_{pq}$ result in $A_{ijpq} = T_{i,j,m,N^2_{pq},N^3_{pq}}$

In [12]:
my_array_i_j_k_m = np.random.normal(0,10, size=(50,40,90,60))


dim2_indeces_p_q = np.random.randint(0,9, size=(2,3))
dim3_indeces_p_q = np.random.randint(0,6, size=(2,3))
my_array_p_q_j_k = my_array_i_j_k_m[:,:,dim2_indeces_p_q,dim3_indeces_p_q]
print(my_array_p_q_j_k.shape)

(50, 40, 2, 3)


$T_{ijkm}, N^0_{pq},N^3_{pq}$ result in $A_{pqjm} = T_{N^0_{pq},j,m,,N^3_{pq}}$



In [13]:
my_array_i_j_k_m = np.random.normal(0,10, size=(50,40,90,60))


dim0_indeces_p_q = np.random.randint(0,4, size=(2,3))
dim3_indeces_p_q = np.random.randint(0,6, size=(2,3))
my_array_p_q_j_k = my_array_i_j_k_m[dim0_indeces_p_q,:,:,dim3_indeces_p_q]
print(my_array_p_q_j_k.shape)

(2, 3, 40, 90)


$T_{ijk},$ $N^0_{p\cdot}$ $N^0_{\cdot q}$ get where by $N^0_{p\cdot}$ we mean the tensor is constant in the second dimension, obtain $A_{pqj} = T_{N^0_{p \cdot},j,N^0_{ \cdot q} }$

In [14]:
my_array_i_j_k = np.random.normal(0,10, size=(50,40,90))

row_indeces_p = np.random.randint(0,5, size= 3)
column_indeces_q = np.random.randint(0,9, size= 2 )

my_array_p_q_j= my_array_i_j_k[row_indeces_p[:,None],: ,column_indeces_q[None,:]]

print(my_array_p_q_j.shape)

(3, 2, 40)


Boolean Indexing

Now say you got tensor $T_{i_1,\dots,i_d}$ and a 1D boolen vectors $b$ with having the same lenght as the dimension say $i_1$ of $T$. We want to get $T_{i_1,\dots,i_d}$ restricted to $i_1$ such that $b_{i_1} is True.

In [15]:
np.random.seed(42)
my_array_i_j_k_m = np.random.randint(-10,10, size=(10,9,5,8))

my_rows_i = np.random.randint(0,2, size=(10), dtype= bool)
my_columns_k = np.random.randint(0,2, size=(5), dtype= bool)

my_sub_array = my_array_i_j_k_m[my_rows_i][:,:,my_columns_k]
my_sub_array.shape

(3, 9, 1, 8)

Reshaping and flattening

$A_{i,j,k}$ of shape $N \times M \times K$ ---> $A_{ij,k}$ of shape $NM \times K$

In [16]:
np.random.seed(42)
my_array_i_j_k = np.random.randint(-10,10, size=(10,5,6))
my_array_ij_k = my_array_i_j_k.reshape(50,6)

print(my_array_ij_k.shape)

(50, 6)


$A_{i,j,k}$ of shape $N \times M \times K$ ---> $A_{ijk}$ of shape $NMK$

In [17]:
my_array_i_j_k.flatten().shape

(300,)

$A_{i,j}$ of shape $N \times M$  ---> $A_{ij}$ of shape $NM$

In [18]:
np.random.seed(42)
my_array_i_j = np.random.randint(-10,10, size=(2,3))
print(my_array_i_j)
print('-----------------')
print(my_array_i_j.reshape(6))
print('-----------------')
print(my_array_i_j.flatten())

[[-4  9  4]
 [ 0 -3 -4]]
-----------------
[-4  9  4  0 -3 -4]
-----------------
[-4  9  4  0 -3 -4]


# Element-wise Operations and Vectorization

addition, multiplication, division

$C_{ij} = A_{ij} + B_{ij}$

In [19]:
np.random.seed(42)
my_array_i_j = np.random.randint(-10,10, size=(2,3))
my_other_array_i_j = np.random.randint(-10,10, size=(2,3))
print(my_array_i_j)
print('+')
print(my_other_array_i_j)
print('=')
print(my_array_i_j + my_other_array_i_j)

[[-4  9  4]
 [ 0 -3 -4]]
+
[[ 8  0  0]
 [-7 -3 -8]]
=
[[  4   9   4]
 [ -7  -6 -12]]


$T_{i,j,k} = A_{i,j,k}  B_{i,j}$

In [20]:
np.random.seed(42)
A_i_j_k = np.random.randint(-10,10, size=(10,3,12))
B_i_j = np.random.randint(-10,10, size= (10,3))

T_i_j_k = (A_i_j_k * B_i_j[:,:,None])

print(T_i_j_k.shape)

(10, 3, 12)


# Matrix operations and Linear Algebra

Matrix multiplication is @. This works on tensors like this: given tensors
$ A_{i_d,\dots,i_1 , j_1,j_2}$ and $ B_{i_{d'},\dots,i_1 , j_2,j_3}$ with dimensions $i_1,\dots i_{\min\{d,d'\}}$ of the same lenght and the last 2 organized as shown (last of dimension of $A$ matches second to last dimension in $B$). Then M = A @ B is $M_{i_{\max\{d,d'\}},\dots,i_1 , j_1,j_3} = \sum_{j_2}A_{i_d,\dots,i_1 , j_1,j_2} B_{i_{d'},\dots,i_1 , j_2,j_3}.$

$M_{i,j,\ell} = \sum_{k} A_{i,j,k} B_{k,\ell}$

In [21]:
A_i_j_k = np.random.rand(30,20,5)
B_k_l = np.random.rand(5,7)

M_i_j_l = (A_i_j_k @ B_k_l)
print(M_i_j_l.shape)

(30, 20, 7)


$M_{i,j,\ell} = \sum_{k} A_{i,j,k} B_{i,k,\ell}$

In [22]:
A_i_j_k = np.random.rand(30,20,5)
B_i_k_l = np.random.rand(30,5,7)

M_i_j_l = (A_i_j_k @ B_i_k_l)
print(M_i_j_l.shape)

(30, 20, 7)


$M_{p,i,j,\ell} = \sum_{k} A_{i,j,k} B_{p,k,\ell}$

In [23]:
A_i_j_k = np.random.rand(30,20,5)
B_p_k_l = np.random.rand(100,5,7)

M_p_i_j_l = (A_i_j_k @ B_p_k_l[:,None,:,:])
print(M_p_i_j_l.shape)

(100, 30, 20, 7)


np.linalg contains many of linear algebra functions. Solve linear systems (np.linalg.solve) finding eigenvalues (np.linalg.eig()), computing determinant (np.linalg.det())...

In [24]:
A = np.random.rand(10,10)
b = np.random.rand(10)

x = np.linalg.solve(A,b)
print(np.all(np.abs(A @ x - b) < 1e-13))

True


# Markov Decision Problems

States $X$ and actions $A$ (finite sets). Flow utility $ u_{ax},$ transition probabilities $P_{axx'}$ and discounta factor $\beta \in [0,1).$ We want to solve
$$ V_x = \max_{a \in A} u_{ax} +\beta \sum_{x' \in X} P_{axx'} V_{x'}$$

In [25]:
num_states = 10
num_actions = 5
beta = 0.9
np.random.seed(42)
u_a_x = np.random.rand(num_actions, num_states)
P_a_x_xp = np.random.rand(num_actions, num_states, num_states)
P_a_x_xp /= P_a_x_xp.sum(2)[:,:,None]

**Value iteration:**


Init: $V_x \in \mathbb{R}$ for each $x$

Repeat
* $V_x ← \max_{a \in A} u_{ax} + \beta \sum_{x' \in X} P_{axx'} V_{x'}$ for each $x$

until a certain tolerance is met.

In [26]:
max_iterations = 1000
V_x = np.zeros(num_states)

for iter in range(max_iterations):
    # Value update
    V_x_new = (u_a_x + beta * P_a_x_xp @ V_x).max(0)

    # If value is almost stationary stop
    if np.abs(V_x - V_x_new).max() < 1e-14:
        print(f'converged in {iter+1} iterations')
        break
    V_x = V_x_new


value_VI = V_x
policy_VI = (u_a_x + beta * P_a_x_xp @ V_x).argmax(0)
print(value_VI.round(2))
print(policy_VI)

converged in 306 iterations
[7.59 7.95 7.74 7.95 7.9  7.82 7.3  7.79 7.69 7.61]
[3 1 1 3 3 3 3 0 3 0]


**Policy iteration:**

Init: $\mu_x \in A$ for each $x$


Repeat:
* (policy evaluation) solve $(I - \beta P^\mu)V = u^\mu$ for $V,$ where $u^\mu_{x} = u_{\mu_x x}$ and similarly for $P^\mu.$
* (policy improvement) $ \mu_x ← \arg\max_{a \in A} u_{ax} + \beta \sum_{x' \in X} P_{axx'} V_x$ for each $x$ (breaking ties in favor of lower indeces).

if the policy does not change (it is stationary) stop.

In [27]:
mu_x = np.zeros(num_states, dtype=int)
max_iter = 40

for iter in range(max_iter):
    # Policy evaluation
    Vmu_x = np.linalg.solve(np.eye(num_states) - beta * P_a_x_xp[mu_x, np.arange(num_states), :],
                            u_a_x[mu_x, np.arange(num_states)])

    # Policy improvement
    mu_x_new = (u_a_x + beta * P_a_x_xp @ Vmu_x).argmax(0)

    # If policy is stationary stop
    if np.all(mu_x == mu_x_new):
        print(f'converged in {iter+1} iterations')
        break

    # Else, continue with mu_x_new
    mu_x = mu_x_new


value_PI = Vmu_x
policy_PI = mu_x
print(value_PI.round(2))
print(policy_PI)

converged in 3 iterations
[7.59 7.95 7.74 7.95 7.9  7.82 7.3  7.79 7.69 7.61]
[3 1 1 3 3 3 3 0 3 0]


Check this link for a discussion on the complexity of policy iteration.
[Planning in MDPs - Lecture 4](https://rltheory.github.io/lecture-notes/planning-in-mdps/lec4/)
